### ISSUE TITLE
bintrayUpload Errors: Cannot find symbol

### ISSUE THREAD

**Issue by ThanosFisherman** [nisrulz/UploadToBintray#1]
Hi,

Whey I try to upload my Android lib to bintray using your gradle config files, I get several warnings and errors coming from the `androidx.annotation:annotation:1.0.0` dependency which I am using in my lib.

for example:

```
error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation

javadoc: warning - Class NonNull not found.
javadoc: warning - Class NonNull not found.
```

Do you know why this is happening?

**Comment by nisrulz** [comment]
How are you including `androidx.annotation:annotation:1.0.0` in your build.gradle file? Please share more context.

**Comment by ThanosFisherman** [comment]
I tried including it in my dependencies using both `api` and `implementation` keyword but it makes no difference. Currently my gradle dependencies look like this.

```groovy
dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0-alpha3', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.annotation:annotation:1.0.0'
    testImplementation 'junit:junit:4.12'
}
```

I must say that the library is uploaded fine nevertheless. It is just those error messages that bother me.

**Comment by nisrulz** [comment]
Yup, the config files don't care about what dependencies you have. If you them, it will just add them to your POM.xml file. Can you also share your generated POM.xml file from bintray?

If not, just check it has the annotations lib under dependencies tag. That means the plugin worked fine. 

The error you get however is because of some other issue. I cannot tell for sure what is causing this problem. 

Remove the exclude line from your espresso deps maybe, I think it might be removing the androidx deps too.

**Comment by ThanosFisherman** [comment]
I tried all of your suggestions and even completely removed the espresso thing but those warnings persist.

![screenshot from 2018-10-04 19-35-52](https://user-images.githubusercontent.com/4888330/46488970-deec7000-c80c-11e8-8d2c-391e4ca5c032.png)

The generated pom.xml already includes the annotation dependency so at least the plugin is working.
```
  <dependencies>
    <dependency>
      <groupId>androidx.annotation</groupId>
      <artifactId>annotation</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

**Comment by nisrulz** [comment]
Looks like there is some issue with Javadoc plugin. You should ask this question stackoverflow.

**Comment by ThanosFisherman** [comment]
I will. Thanks a lot for your help.

**Comment by nisrulz** [comment]
Happy to help wherever possible. 😄 

Closing as not related to this repo.
